In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
from google.colab import files
uploaded=files.upload()

Saving Cleaned_Viral_Social_Media_Trends.csv to Cleaned_Viral_Social_Media_Trends.csv

In [3]:
df=pd.read_csv('Cleaned_Viral_Social_Media_Trends.csv')
df.head()

,Post_ID,Post_Date,Platform,Hashtag,Content_Type,Region,Views,Likes,Shares,Comments,Engagement_Level
0,Post_1,2022-01-13,TikTok,#Challenge,Video,UK,4163464,339431,53135,19346,High
1,Post_2,2022-05-13,Instagram,#Education,Shorts,India,4155940,215240,65860,27239,Medium
2,Post_3,2022-01-07,Twitter,#Challenge,Video,Brazil,3666211,327143,39423,36223,Medium
3,Post_4,2022-12-05,YouTube,#Education,Shorts,Australia,917951,127125,11687,36806,Low
4,Post_5,2023-03-23,TikTok,#Dance,Post,Brazil,64866,171361,69581,6376,Medium

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Post_ID           5000 non-null   object
 1   Post_Date         5000 non-null   object
 2   Platform          5000 non-null   object
 3   Hashtag           5000 non-null   object
 4   Content_Type      5000 non-null   object
 5   Region            5000 non-null   object
 6   Views             5000 non-null   int64
 7   Likes             5000 non-null   int64
 8   Shares            5000 non-null   int64
 9   Comments          5000 non-null   int64
 10  Engagement_Level  5000 non-null   object
dtypes: int64(4), object(7)
memory usage: 429.8+ KB

In [5]:
df.isnull().sum()

Post_ID             0
Post_Date           0
Platform            0
Hashtag             0
Content_Type        0
Region              0
Views               0
Likes               0
Shares              0
Comments            0
Engagement_Level    0
dtype: int64

In [6]:
df['Post_Date'] = pd.to_datetime(df['Post_Date'])

df['day_of_week'] = df['Post_Date'].dt.day_name()
df['month'] = df['Post_Date'].dt.month
df['is_weekend'] = df['Post_Date'].dt.dayofweek >= 5

In [7]:
df = df.drop('Post_Date', axis=1)

In [8]:
#Engagement Rate
df['Engagement_rate']=(df['Likes']+df['Shares']+df['Comments'])/df['Views']
df['Engagement_rate']

0       0.098935
1       0.074192
2       0.109865
3       0.191315
4       3.812752
          ...
4995    0.104595
4996    0.046667
4997    0.070608
4998    0.046264
4999    0.067028
Name: Engagement_rate, Length: 5000, dtype: float64

In [9]:
#Hashtag Count
df['Hashtag']=df['Hashtag'].apply(lambda x: len(str (x).split()))

In [10]:
df.head()

,Post_ID,Platform,Hashtag,Content_Type,Region,Views,Likes,Shares,Comments,Engagement_Level,day_of_week,month,is_weekend,Engagement_rate
0,Post_1,TikTok,1,Video,UK,4163464,339431,53135,19346,High,Thursday,1,False,0.098935
1,Post_2,Instagram,1,Shorts,India,4155940,215240,65860,27239,Medium,Friday,5,False,0.074192
2,Post_3,Twitter,1,Video,Brazil,3666211,327143,39423,36223,Medium,Friday,1,False,0.109865
3,Post_4,YouTube,1,Shorts,Australia,917951,127125,11687,36806,Low,Monday,12,False,0.191315
4,Post_5,TikTok,1,Post,Brazil,64866,171361,69581,6376,Medium,Thursday,3,False,3.812752

In [11]:
df['Virality_Score']=(df['Likes']*0.4+df['Shares']*0.4+df['Comments']*0.2)/df['Views']

In [12]:
df.groupby('Platform')['Engagement_rate'].mean().sort_values(ascending=False)

Platform
Instagram    0.662058
TikTok       0.638711
YouTube      0.506368
Twitter      0.465425
Name: Engagement_rate, dtype: float64

In [13]:
df.groupby('Content_Type')['Engagement_rate'].mean().sort_values(ascending=False)

Content_Type
Shorts         0.806289
Live Stream    0.618768
Tweet          0.520691
Post           0.498066
Video          0.488207
Reel           0.487531
Name: Engagement_rate, dtype: float64

In [14]:
df.groupby('day_of_week')['Engagement_rate'].mean().sort_values(ascending=False)

day_of_week
Sunday       0.946136
Tuesday      0.617597
Friday       0.578791
Wednesday    0.552417
Saturday     0.442771
Monday       0.428716
Thursday     0.404451
Name: Engagement_rate, dtype: float64

In [15]:
df.head()

,Post_ID,Platform,Hashtag,Content_Type,Region,Views,Likes,Shares,Comments,Engagement_Level,day_of_week,month,is_weekend,Engagement_rate,Virality_Score
0,Post_1,TikTok,1,Video,UK,4163464,339431,53135,19346,High,Thursday,1,False,0.098935,0.038645
1,Post_2,Instagram,1,Shorts,India,4155940,215240,65860,27239,Medium,Friday,5,False,0.074192,0.028366
2,Post_3,Twitter,1,Video,Brazil,3666211,327143,39423,36223,Medium,Friday,1,False,0.109865,0.041970
3,Post_4,YouTube,1,Shorts,Australia,917951,127125,11687,36806,Low,Monday,12,False,0.191315,0.068507
4,Post_5,TikTok,1,Post,Brazil,64866,171361,69581,6376,Medium,Thursday,3,False,3.812752,1.505442

In [16]:
df.head()

,Post_ID,Platform,Hashtag,Content_Type,Region,Views,Likes,Shares,Comments,Engagement_Level,day_of_week,month,is_weekend,Engagement_rate,Virality_Score
0,Post_1,TikTok,1,Video,UK,4163464,339431,53135,19346,High,Thursday,1,False,0.098935,0.038645
1,Post_2,Instagram,1,Shorts,India,4155940,215240,65860,27239,Medium,Friday,5,False,0.074192,0.028366
2,Post_3,Twitter,1,Video,Brazil,3666211,327143,39423,36223,Medium,Friday,1,False,0.109865,0.041970
3,Post_4,YouTube,1,Shorts,Australia,917951,127125,11687,36806,Low,Monday,12,False,0.191315,0.068507
4,Post_5,TikTok,1,Post,Brazil,64866,171361,69581,6376,Medium,Thursday,3,False,3.812752,1.505442

In [17]:
df_ = df.drop('Post_ID', axis=1)

In [18]:
df = pd.get_dummies(df, columns=[
    'Platform', 'Content_Type', 'Region', 'day_of_week'
], drop_first=True)

In [19]:
df = df.drop('Hashtag', axis=1)

In [20]:
df = df[df['Likes'] <= df['Views']]

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Engagement_Level'] = le.fit_transform(df['Engagement_Level'])

In [23]:
df.head()

,Post_ID,Views,Likes,Shares,Comments,Engagement_Level,month,is_weekend,Engagement_rate,Virality_Score,...,Region_India,Region_Japan,Region_UK,Region_USA,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,day_of_week_Wednesday
0,Post_1,4163464,339431,53135,19346,0,1,False,0.098935,0.038645,...,False,False,True,False,False,False,False,True,False,False
1,Post_2,4155940,215240,65860,27239,2,5,False,0.074192,0.028366,...,True,False,False,False,False,False,False,False,False,False
2,Post_3,3666211,327143,39423,36223,2,1,False,0.109865,0.041970,...,False,False,False,False,False,False,False,False,False,False
3,Post_4,917951,127125,11687,36806,1,12,False,0.191315,0.068507,...,False,False,False,False,True,False,False,False,False,False
5,Post_6,1323566,136282,86979,47129,1,11,False,0.204289,0.074594,...,False,False,False,False,False,False,False,False,False,True

In [24]:
df = df.astype({col: 'int' for col in df.select_dtypes('bool').columns})

In [25]:
df.head()

,Post_ID,Views,Likes,Shares,Comments,Engagement_Level,month,is_weekend,Engagement_rate,Virality_Score,...,Region_India,Region_Japan,Region_UK,Region_USA,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,day_of_week_Wednesday
0,Post_1,4163464,339431,53135,19346,0,1,0,0.098935,0.038645,...,0,0,1,0,0,0,0,1,0,0
1,Post_2,4155940,215240,65860,27239,2,5,0,0.074192,0.028366,...,1,0,0,0,0,0,0,0,0,0
2,Post_3,3666211,327143,39423,36223,2,1,0,0.109865,0.041970,...,0,0,0,0,0,0,0,0,0,0
3,Post_4,917951,127125,11687,36806,1,12,0,0.191315,0.068507,...,0,0,0,0,1,0,0,0,0,0
5,Post_6,1323566,136282,86979,47129,1,11,0,0.204289,0.074594,...,0,0,0,0,0,0,0,0,0,1

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [27]:
X = df.drop('Engagement_Level', axis=1)
y = df['Engagement_Level']

In [28]:
X = pd.get_dummies(X, drop_first=True)

In [29]:
X = X.astype(int)

In [30]:
xtrain, xtest, ytrain, ytest = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [31]:
model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    random_state=42
)

In [32]:
model.fit(xtrain, ytrain)

RandomForestClassifier(n_estimators=300, random_state=42)

In [33]:
ypred = model.predict(xtest)

In [34]:
print("Accuracy:", accuracy_score(ytest, ypred))
print(classification_report(ytest, ypred))

Accuracy: 0.3345070422535211
              precision    recall  f1-score   support

           0       0.34      0.37      0.35       480
           1       0.35      0.40      0.37       497
           2       0.31      0.22      0.26       443

    accuracy                           0.33      1420
   macro avg       0.33      0.33      0.33      1420
weighted avg       0.33      0.33      0.33      1420

In [35]:


print(df.groupby('Engagement_Level')['Engagement_rate'].mean())

Engagement_Level
0    0.207931
1    0.202881
2    0.199514
Name: Engagement_rate, dtype: float64

In [41]:
joblib.dump(model, "viral_model.pkl")
joblib.dump(X.columns.tolist(), "model_columns.pkl")
joblib.dump(le, "label_encoder.pkl")

print("✅ Model + files saved successfully!")

✅ Model + files saved successfully!

In [38]:
!pip install streamlit

Collecting streamlit
  Downloading streamlit-1.56.0-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.18.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.56.0-py3-none-any.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 49.5 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 51.8 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.1 streamlit-1.56.0

In [39]:
import streamlit as st
import pandas as pd
import joblib

In [42]:
# Load model + columns
model = joblib.load("viral_model.pkl")
columns = joblib.load("model_columns.pkl")
le = joblib.load("label_encoder.pkl")

In [43]:
st.title("📊 AI Viral Content Analyzer")

2026-04-08 15:31:06.673 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:06.927
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]
2026-04-08 15:31:06.930 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:06.934 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [44]:
likes = st.number_input("Likes", value=100)
shares = st.number_input("Shares", value=50)
comments = st.number_input("Comments", value=20)
views = st.number_input("Views", value=1000)

2026-04-08 15:31:25.707 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.708 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.709 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.710 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.711 Session state does not function when running a script without `streamlit run`
2026-04-08 15:31:25.712 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.713 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.715 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.716 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.716 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.717 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.718 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.719 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.719 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.720 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.721 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.722 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.722 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.723 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.724 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.725 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.725 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.727 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.727 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.728 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.728 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:25.730 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [45]:

platform = st.selectbox("Platform", ["Instagram", "YouTube", "Twitter"])
content_type = st.selectbox("Content Type", ["Reel", "Post", "Video"])
region = st.selectbox("Region", ["India", "USA", "UK"])

2026-04-08 15:31:43.570 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:31:43.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [46]:
input_dict = {
    'Likes': likes,
    'Shares': shares,
    'Comments': comments,
    'Views': views,
    'Hashtag': 5,
    'Engagement_rate': (likes + shares + comments) / views if views > 0 else 0,
    'Virality_Score': (likes*0.4 + shares*0.4 + comments*0.2) / views if views > 0 else 0
}

input_df = pd.DataFrame([input_dict])

In [47]:
# Convert categorical
input_df['Platform'] = platform
input_df['Content_Type'] = content_type
input_df['Region'] = region

In [48]:
# One-hot encoding
input_df = pd.get_dummies(input_df)

# Match training columns
input_df = input_df.reindex(columns=columns, fill_value=0)

In [49]:
# Prediction
# -------------------------------
if st.button("Predict"):
    pred = model.predict(input_df)
    result = le.inverse_transform(pred)[0]

    if result == "High":
        st.success("🔥 High Engagement (Viral)")
    elif result == "Medium":
        st.warning("⚡ Medium Engagement")
    else:
        st.error("⚠️ Low Engagement")

2026-04-08 15:32:52.847 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:32:52.849 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:32:52.850 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:32:52.851 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:32:52.852 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 15:32:52.852 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [50]:
%%writefile app.py
import streamlit as st
import pandas as pd
import joblib

model = joblib.load("viral_model.pkl")
columns = joblib.load("model_columns.pkl")
le = joblib.load("label_encoder.pkl")

st.title("AI Viral Content Analyzer")

likes = st.number_input("Likes", value=100)
shares = st.number_input("Shares", value=50)
comments = st.number_input("Comments", value=20)
views = st.number_input("Views", value=1000)

platform = st.selectbox("Platform", ["Instagram", "YouTube", "Twitter"])
content_type = st.selectbox("Content Type", ["Reel", "Post", "Video"])
region = st.selectbox("Region", ["India", "USA", "UK"])

input_dict = {
    'Likes': likes,
    'Shares': shares,
    'Comments': comments,
    'Views': views,
    'Hashtag': 5,
    'Engagement_rate': (likes + shares + comments) / views if views > 0 else 0,
    'Virality_Score': (likes*0.4 + shares*0.4 + comments*0.2) / views if views > 0 else 0,
    'Platform': platform,
    'Content_Type': content_type,
    'Region': region
}

df = pd.DataFrame([input_dict])
df = pd.get_dummies(df)
df = df.reindex(columns=columns, fill_value=0)

if st.button("Predict"):
    pred = model.predict(df)
    result = le.inverse_transform(pred)[0]
    st.write("Prediction:", result)

Writing app.py

In [51]:

!pip install streamlit pyngrok

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.56.0)
Collecting pyngrok
  Downloading pyngrok-8.0.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.1)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.18.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading pyngrok-8.0.0-py3-none-any.whl (24 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-8.0.0

In [52]:
!streamlit run app.py &>/dev/null &

In [54]:
!ngrok config add-authtoken 3C5BZyIdTBTm15UbguCfNb9hjtW_oAn8DXeSuvUms6E5k943

Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml

In [55]:
from pyngrok import ngrok

url = ngrok.connect(8501)
print(url)

NgrokTunnel: "https://figgiest-upstanding-carmon.ngrok-free.dev" -> "http://localhost:8501"